services:
  - type: web
    name: bajaj-test-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
